#!/bin/bash

# Usage: token-burn <repo-path> <token type> <amount>
#
# repo-path: absolute path of the author repository
# token type: hash of the token
# amount: the number of tokens that should be burned
#
#
# Creates the number of tokens for this account
# 
# Exists with exit code 0 on success or exit code 1 on error. If the account has insufficient balance, error code 2 is returned.

SCRIPTDIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
REPO_PATH=$1
TOKEN_TYPE=$2
AMOUNT=$3

# check input arguments
if test ! -d $REPO_PATH; then
    echo "Invalid repo path '$REPO_PATH'" >&2
    exit 1
fi

cd $REPO_PATH
AUTHOR_ID="$(git config goc.author.id)"

if [ -z $AUTHOR_ID ]; then
    echo "The repository misses goc.author.id" >&2
    exit 1
fi

if [ -z $AMOUNT ] || [ "$(python3 -c "print($AMOUNT <= 0)" )" = "True" ]; then
    echo "Amount is less equal 0" >&2
    exit 1
fi

if [ "$(git cat-file -t $TOKEN_TYPE 2>/dev/null)" = "commit" ]; then
    if [ "$(git show -s --format=%p $TOKEN_TYPE | wc -w)" -ne 0 ]; then
        echo "Token Type '$TOKEN_TYPE' unknown." >&2
    fi
else
    echo "Token Type '$TOKEN_TYPE' unknown." >&2
fi


#check balance
balance=$($SCRIPTDIR/account-balance $REPO_PATH $TOKEN_TYPE $AUTHOR_ID 2>/dev/null)

if [ $(python3 -c "print($balance < $AMOUNT)") = "True" ]; then
    echo "The account has an insufficient number of tokens to burn." >&2
    exit 1
fi

#calculate new burn counter
checkpoint=$($SCRIPTDIR/account-checkpoint $REPO_PATH $TOKEN_TYPE $AUTHOR_ID)
if [ -z $checkpoint ]; then
    echo "error while creating checkpoint" >&2
    exit 1
fi
burned_blob=$(git ls-tree $checkpoint burned | awk '{print $3}')
burned=$(git cat-file -p $burned_blob)

new_amount=$(python3 -c "print($burned + $AMOUNT)")


#create commit
blob=$(echo $new_amount | git hash-object --stdin -w)
tree_str="$($SCRIPTDIR/utility/ls-tree-format -b $blob:burned)"
tree=$(echo -e $tree_str | git mktree)

# debug message (if enabled)
commit_mgs=""
if [ "$(git config --bool goc.debug)" = "true" ]; then
    commit_mgs="burn($TOKEN_TYPE/$AUTHOR_ID, $AMOUNT)"
fi

commit=$(echo "$commit_mgs" | GIT_COMMITTER_NAME="$AUTHOR_ID" GIT_AUTHOR_NAME="$AUTHOR_ID" GIT_COMMITTER_EMAIL="" GIT_AUTHOR_EMAIL="" git commit-tree -S $tree -p refs/heads/frontier/$TOKEN_TYPE/$AUTHOR_ID)
git update-ref "refs/heads/frontier/$TOKEN_TYPE/$AUTHOR_ID" "$commit"

echo "Burned $AMOUNT tokens of type '$TOKEN_TYPE' for author '$AUTHOR_ID'"
