#!/bin/bash

# Usage: token-burn <repo-path> <token type> <amount>
#
# repo-path: absolute path of the author repository
# token type: hash of the token
# amount: the number of tokens that should be burned
#
#
# Creates the number of tokens for this account
# 
# Exists with exit code 0 on success or exit code 1 on error. If the account has insufficient balance, error code 2 is returned.

SCRIPTDIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
REPO_PATH=$1
TOKEN_TYPE=$2
AMOUNT=$3

# check input arguments
if test ! -d $REPO_PATH; then
    echo "Invalid repo path '$REPO_PATH'" >&2
    exit 1
fi

cd $REPO_PATH
AUTHOR_ID="$(git config goc.author.id)"

if [ -z $AUTHOR_ID ]; then
    echo "The repository misses goc.author.id" >&2
    exit 1
fi

if [ -z $AMOUNT ] || [ "$(python3 -c "print($AMOUNT <= 0)" )" = "True" ]; then
    echo "Amount is less equal 0" >&2
    exit 1
fi

if [ "$(git cat-file -t $TOKEN_TYPE 2>/dev/null)" = "commit" ]; then
    if [ "$(git show -s --format=%p $TOKEN_TYPE | wc -w)" -ne 0 ]; then
        echo "Token Type '$TOKEN_TYPE' unknown." >&2
    fi
else
    echo "Token Type '$TOKEN_TYPE' unknown." >&2
fi

#check balance
BALANCE=$($SCRIPTDIR/account-balance $REPO_PATH $TOKEN_TYPE $AUTHOR_ID)

if [ $(python3 -c "print($BALANCE < $AMOUNT)") = "True" ]; then
    echo "The account has an insufficient number of tokens to burn." >&2
    exit 1
fi

#get current burned amount
BURNED=0
ACCOUNT_REF=$(git show-ref --hash refs/heads/frontier/$TOKEN_TYPE/$AUTHOR_ID)

if [ ! -z $ACCOUNT_REF ]; then
    BURNED_BLOB=$(git ls-tree $ACCOUNT_REF burned | awk '{print $3}')
    BURNED=$(git cat-file -p $BURNED_BLOB)

    # other fields dind't change:
    CREATED_BLOB=$(git ls-tree $ACCOUNT_REF created | awk '{print $3}')
    GIVEN_TO_TREE=$(git ls-tree $ACCOUNT_REF giveTo | awk '{print $3}')
    ACK_FROM_TREE=$(git ls-tree $ACCOUNT_REF ackFrom | awk '{print $3}')
else
    # initialize other fields:
    ZERO_BLOB=$(echo "0" | git hash-object --stdin -w )
    EMPTY_TREE=$(git hash-object -w -t tree /dev/null)

    CREATED_BLOB=$ZERO_BLOB
    GIVEN_TO_TREE=$EMPTY_TREE
    ACK_FROM_TREE=$EMPTY_TREE
fi

# calculate new burn amount
NEW_AMOUNT=$(python3 -c "print($BURNED + $AMOUNT)")
BLOB=$(echo $NEW_AMOUNT | git hash-object --stdin -w)


#create commit
TREE_STR="$($SCRIPTDIR/utility/ls-tree-format -b $CREATED_BLOB:created -b $BLOB:burned -t $GIVEN_TO_TREE:giveTo -t $ACK_FROM_TREE:ackFrom)"
TREE=$(echo -e $TREE_STR | git mktree)

# debug message (if enabled)
commit_mgs=""
if [ "$(git config --bool goc.debug)" = "true" ]; then
    commit_mgs="burn($TOKEN_TYPE/$AUTHOR_ID, $AMOUNT)"
fi

COMMIT=$(echo "$commit_mgs" | GIT_COMMITTER_NAME="$AUTHOR_ID" GIT_AUTHOR_NAME="$AUTHOR_ID" GIT_COMMITTER_EMAIL="" GIT_AUTHOR_EMAIL="" git commit-tree -S $TREE -p refs/heads/frontier/$TOKEN_TYPE/$AUTHOR_ID)
git update-ref "refs/heads/frontier/$TOKEN_TYPE/$AUTHOR_ID" "$COMMIT"

echo "Burned $AMOUNT tokens of type '$TOKEN_TYPE' for author '$AUTHOR_ID'"