#!/bin/bash

# Usage: token-create <repo-path> <token type> <amount>
#
# repo-path: absolute path of the author repository
# token type: hash of the token
# amount: the number of tokens that should be created
#
#
# Creates the number of tokens for this account

SCRIPTDIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
REPO_PATH=$1
TOKEN_TYPE=$2
AMOUNT=$3

# check input arguments
if test ! -d $REPO_PATH; then
    echo "Invalid repo path '$REPO_PATH'" >&2
    exit 1
fi

cd $REPO_PATH
AUTHOR_ID="$(git config goc.author.id)"

if [ -z $AUTHOR_ID ]; then
    echo "The repository misses goc.author.id" >&2
    exit 1
fi

if [ -z $AMOUNT ] || [ "$(python3 -c "print($AMOUNT <= 0)" )" = "True" ]; then
    echo "Amount is less equal 0" >&2
    exit 1
fi

if [ "$(git cat-file -t $TOKEN_TYPE 2>/dev/null)" = "commit" ]; then
    if [ "$(git show -s --format=%p $TOKEN_TYPE | wc -w)" -ne 0 ]; then
        echo "Token Type '$TOKEN_TYPE' unknown." >&2
    fi
else
    echo "Token Type '$TOKEN_TYPE' unknown." >&2
fi

#get current created amount
CREATED=0
ACCOUNT_REF=$(git show-ref --hash refs/heads/frontier/$TOKEN_TYPE/$AUTHOR_ID)

if [ ! -z $ACCOUNT_REF ]; then
    CREATED_BLOB=$(git ls-tree $ACCOUNT_REF created | awk '{print $3}')
    CREATED=$(git cat-file -p $CREATED_BLOB)

    # other fields dind't change:
    BURNED_BLOB=$(git ls-tree $ACCOUNT_REF burned | awk '{print $3}')
    GIVEN_TO_TREE=$(git ls-tree $ACCOUNT_REF giveTo | awk '{print $3}')
    ACK_FROM_TREE=$(git ls-tree $ACCOUNT_REF ackFrom | awk '{print $3}')
else
    # initialize other fields:
    ZERO_BLOB=$(echo "0" | git hash-object --stdin -w )
    EMPTY_TREE=$(git hash-object -w -t tree /dev/null)

    BURNED_BLOB=$ZERO_BLOB
    GIVEN_TO_TREE=$EMPTY_TREE
    ACK_FROM_TREE=$EMPTY_TREE
fi

#create commit
NEW_AMOUNT=$(python3 -c "print($CREATED + $AMOUNT)")
BLOB=$(echo $NEW_AMOUNT | git hash-object --stdin -w)

TREE_STR="$($SCRIPTDIR/utility/ls-tree-format -b $BLOB:created -b $BURNED_BLOB:burned -t $GIVEN_TO_TREE:giveTo -t $ACK_FROM_TREE:ackFrom)"
TREE=$(echo -e $TREE_STR | git mktree)

# debug message (if enabled)
commit_mgs=""
if [ "$(git config --bool goc.debug)" = "true" ]; then
    commit_mgs="create($TOKEN_TYPE/$AUTHOR_ID, $AMOUNT)"
fi

parent=$(git show-ref --hash refs/heads/frontier/$TOKEN_TYPE/$AUTHOR_ID)
if [ -z $parent ]; then
    parent=$TOKEN_TYPE
fi

COMMIT=$(echo "$commit_mgs" | GIT_COMMITTER_NAME="$AUTHOR_ID" GIT_AUTHOR_NAME="$AUTHOR_ID" GIT_COMMITTER_EMAIL="" GIT_AUTHOR_EMAIL="" git commit-tree -S $TREE -p $parent)
git update-ref "refs/heads/frontier/$TOKEN_TYPE/$AUTHOR_ID" "$COMMIT"

echo "Created $AMOUNT tokens of type '$TOKEN_TYPE' for author '$AUTHOR_ID'"